include(CMakePrintHelpers)
file(READ "${CMAKE_CURRENT_LIST_DIR}/project_json_testing.json" json_contents)
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/../CMakeJSON/layouts/project_layout.txt" layout_contents 
             REGEX [=[^([a-z]*;)*[a-z]*:(NUMBER|STRING((:[a-zA-Z0-9]+)(\|[[a-zA-Z0-9]+))?|BOOLEAN|ARRAY|OBJECT)(;OPTIONAL)? ]=])
set(sanitzed_layout)
foreach(line IN LISTS layout_contents)
    string(REGEX REPLACE " +#.*" "" line "${line}")
    string(REGEX REPLACE [[;]] "_" variable_name "${line}")
    string(PREPEND variable_name "CMakeJSON_Layout_")
    string(REGEX REPLACE ":[a-zA-Z]" "" variable_name "${variable_name}")
    set(${variable_name}_INFO )
    string(REGEX REPLACE [[;]] "\\\;" line "${line}")
    message(STATUS "${variable_name} : ${line}")
    list(APPEND sanitzed_layout "${line}")
endforeach()




string(JSON length ERROR_VARIABLE err LENGTH "${json_contents}")
message(STATUS "Layout of JSON contents:'${sanitzed_layout}'")
message(STATUS "Length of JSON contents:'${length}'")
math(EXPR length "${length}-1")
foreach(json_index RANGE ${length})
    string(JSON member ERROR_VARIABLE err MEMBER "${json_contents}" ${json_index})
    if(err)
        cmake_print_variables(err)
    endif()
    string(JSON type ERROR_VARIABLE err TYPE "${json_contents}" ${member})
    if(err)
        cmake_print_variables(err)
    endif()
    list(FIND sanitzed_layout "project;${member}:${type}" found_index)
    if(found_index LESS 0)
        message(WARNING "Unknwon JSON member: project\;${member}:${type}")
    endif()
    string(JSON value ERROR_VARIABLE err GET "${json_contents}" ${member})
    if(err)
        cmake_print_variables(err)
    endif()

    message(STATUS "Member at index '${json_index}': '${member}':'${type}' = '${value}'")
endforeach()
